---
pipeline:
    test:5.6:
        image: php:5.6
        commands:
            - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            - php composer-setup.php
            - php -r "unlink('composer-setup.php');"
            - php composer.phar install
            - ./vendor/bin/phpunit
            - rm composer.phar
    test:7.2:
        image: php:7.2
        commands:
            - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            - php composer-setup.php
            - php -r "unlink('composer-setup.php');"
            - php composer.phar install
            - ./vendor/bin/phpunit
            - rm composer.phar
